name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run frontend tests
        run: cd src && npm test

      - name: Install backend dependencies
        run: cd server && npm ci

      - name: Run backend tests
        run: cd server && npm test
